ScoreBoard
esx-framework/es_extended pull request #1079
Opened 2021-01-30 17:02 UTC by FBFezz

## Proposed Changes

- Added Scoreboard module to base folder

2021-01-30 18:42 UTC, TasoOneAsia requested changes
In general there are a couple things that should probably be changed regarding NUI functionality that I can comment on, but I also left some general comments in the Lua portion even though that's a little outside my scope 😛 . Izio and Ark can further comment on the Lua portion but good start!

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/data/html/index.html
> +  <meta name="generator" content="Google Web Designer 10.0.2.0105">
Unnecessary meta tags

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/data/html/index.html
> +      font-family: "Trebuchet MS";
Try to use a nicer font than Trebuchet MS, this looks a little dull and is easily changed to something more appealing to the eye.

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/data/html/index.html
> +  <style type="text/css" id="gwd-text-style">
Try to split this whole styles section into its own `styles.css` file for example, having everything in index.html is a little cluttered and unnecessary

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/data/html/index.html
> +    .gwd-div-14az {
These class names are clearly being generated by some sort of designer and this lowers maintainability in the future by forcing maintainers to either decipher class names or to use the designer that you are also using. I suggest refactoring the class names to be more descriptive for the styles and elements they are being applied to

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/data/html/index.html
> +        var table = $('.tbl-content');
I prefer we not use var whenever possible as I had previously pinned in the #staff-development channel chat.

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/client/module.lua
> +    table.insert(header, '<tr><th>Name</th><th>RP-Name</th><th>ID</th><th>Ping</th></tr>')
I have a couple of questions regarding this flow. 

1. What's the reasoning for this being a table that holds a single item?
2. Why is this being done in the Lua portion considering it is an HTML element that you wish to render at a further point in the JS? I would suggest maybe moving to portion to the JS as that makes sense for the flow

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/data/html/index.html
> +  <script>
As with the `styles.css` suggestion I made above, it would be better if you could move this into its own `script.js` file.

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/server/main.lua
> +module.Init()
This is calling an empty function.

2021-01-30 18:42 UTC, TasoOneAsia commented on modules/__base__/scoreboard/server/module.lua
> +function Sanitize(str)
Would prefer this be done in the JS portion as well, if you are planning to sanitize.

2021-01-30 18:55 UTC, Mycroft-Studios commented on modules/__base__/scoreboard/data/html/index.html
> +  <meta name="generator" content="Google Web Designer 10.0.2.0105">
Currently there while it's in the designing phase, will be removed after

2021-01-30 19:04 UTC, Mycroft-Studios commented on modules/__base__/scoreboard/client/module.lua
> +    table.insert(header, '<tr><th>Name</th><th>RP-Name</th><th>ID</th><th>Ping</th></tr>')
Going to be Used at a later point to allow for the different themes to not have different lua sections

2021-01-30 19:04 UTC, Mycroft-Studios commented on modules/__base__/scoreboard/server/main.lua
> +module.Init()
Doesn't load if removed

2021-04-30 10:53 UTC, ESXCrackhead commented
Closing for now, since another pr with scoreboard was created and merged.

2021-04-30 10:53 UTC, closed without merging